version: '3.3'
services:
  local-db:
    image: postgres
    container_name: local-db
    restart: always
    ports:
      - '6432:5432'
      # debugging port
      #- '9229:9229'
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: local
    volumes:
      - local_postgres:/var/lib/postgresql/data
    networks:
      - local-network

volumes:
  local_postgres:
    driver: local

networks:
  local-network:
    external: true
