version: '3.3'
services:
  customuse-api:
    image: node:18
    container_name: server
    restart: always
    command: sh -c 'cd /api/ && npm ic && npm run build && make migrate'
    volumes:
      - ./:/api/
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - local-db
    networks:
      - local-network

  local-db:
    image: postgres:12
    container_name: local-db
    ports:
      - '6432:5432'
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: local
    volumes:
      - loacl_postgres:/var/lib/postgresql/data
    networks:
      - local-network

volumes:
  local_postgres:
    driver: local

networks:
  local-network:
    external: true
