version: '3.3'
services:
  server:
    image: node:18-alpine3.16
    platform: linux/amd64
    container_name: server
    restart: always
    command: sh -c 'cd /api/ && npm ic && npm run build && npm run typeorm:migrate && npm run start:dev'
    volumes:
      - ./:/api/
    ports:
      - '3000:3000'
    depends_on:
      - local-db
    environment:
      DB_HOST: host.docker.internal
    networks:
      - local-network

  web:
    image: node:18
    container_name: web
    restart: always
    command: sh -c 'cd /web/ && npm ic && npm run build && npm run preview -- --host'
    # network_mode: 'host'
    volumes:
      - ../web:/web/
    ports:
      - '4173:4173'
    networks:
      - local-network

  local-db:
    image: postgres
    container_name: local-db
    ports:
      - '6432:5432'
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: local
    volumes:
      - local_postgres:/var/lib/postgresql/data
    networks:
      - local-network

volumes:
  local_postgres:
    driver: local

networks:
  local-network:
    external: true
